tag-template: 'draft'
change-template: "* $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'enhancement'
  default: patch
categories:
  - title: 'Features and Enhancements'
    label:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'dependencies'
template: |
  ## What’s Changed

  $CHANGES