name: Pull Request Build

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Run Unit Tests
        run: mvn -B -Pjacoco clean verify install --file pom.xml -e -fae -T 1C
      - name: upload files
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-files
          path: ./**/jacoco.xml
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Run Checkstyle
        run: mvn -B validate --file pom.xml -e -fae
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  sonarcloud:
    needs:
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: jacoco-files
          path: ./jacoco-files/
      - name: Create settings file
        uses: InstaCode/maven-settings-xml-action@v9
        with:
          profiles: '[{ "id": "sonar", "properties": { "sonar.organization":"magenic", "sonar.host.url":"https://sonarcloud.io", "sonar.login": "${{secrets.SONAR_LOGIN}}" }}]'
      - name: Build Packages
        run: mvn -B package -DskipTests=true --file pom.xml -e -fae
      - name: Run SonarCloud Analysis
        run: mvn -B -Psonar sonar:sonar --file pom.xml -e -fae
