name: Pull Request Build

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Create settings file
        uses: s4u/maven-settings-action@v2.1.0
        with:
          properties: '[{ "id": "sonar", "properties": { "sonar.organization":"magenic", "sonar.host.url":"https://sonarcloud.io", "sonar.login": "${{secrets.SONAR_LOGIN}}" }}]'
      - name: Run Unit Tests
        run: mvn -B -X clean install --file pom.xml -e -fae
      - name: Run SonarCloud Analysis
        run: mvn -B -X -Psonar sonar:sonar --file pom.xml -e -fae
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Run Checkstyle
        run: mvn -B validate --file pom.xml -e -fae
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

    #TODO:
    # - Add lockdown
    #X - SonarCloud properties
    #X - caching
