name: Pull Request Build

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up XVFB for UI tests
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Create settings file
        uses: InstaCode/maven-settings-xml-action@v9
        with:
          profiles: '[{ "id": "sonar", "properties": { "sonar.organization":"magenic", "sonar.host.url":"https://sonarcloud.io", "sonar.login": "${{secrets.SONAR_LOGIN}}" }}]'
          servers: '[{"id": "github", "username": "jason-edstrom", "password": "${{secrets.PACKAGES}}"}]'
      - name: Run Unit Tests and SonarCloud Analysis
        run: xvfb-run mvn -B -Pjacoco -Psonar verify package sonar:sonar --file pom.xml -e -fae -Dsonar.coverage.jacoco.xmlReportPaths="${{github.workspace}}/jmaqs-jacoco-reporting/target/site/jacoco-aggregate/jacoco.xml" -T 1C
      - name: Upload Test Result Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: ./**/logs
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore Local Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Run Checkstyle
        run: mvn -B validate --file pom.xml -e -fae
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"