name: Release Pipeline

on:
  push:
  tags:
    -v*


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Create settings file
        uses: InstaCode/maven-settings-xml-action@v9
        with:
          servers: '[{"id": "ossrh", "username": "jason-edstrom", "password": "${{secrets.OSSRH_PACKAGES}}"},{"id": "github", "username": "jason-edstrom", "password": "${{secrets.PACKAGES}}"}]'
          profiles: '[{ "id": "sonar", "properties": { "sonar.organization":"magenic", "sonar.host.url":"https://sonarcloud.io", "sonar.login": "${{secrets.SONAR_LOGIN}}"}}]'
      - name: Set Version to ${{env.VERSION}}-SNAPSHOT and Run Unit Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -Drevision="${{env.VERSION}}-SNAPSHOT" -Dtesting -T 1C verify install sonar:sonar -B -e -f pom.xml -fae -Dsonar.coverage.jacoco.xmlReportPaths="${{github.workspace}}/jmaqs-jacoco-reporting/target/site/jacoco-aggregate/jacoco.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Release Packages to Sonatype - Open Source
        run: mvn -Drevision="${{env.VERSION}}" -Possrh -Drelease deploy -B -e -f pom.xml
      - name: Deploy Release Packages to GitHub Packages
        run: mvn -Drevision="${{env.VERSION}}" -Pgithub -Drelease deploy -B -e -f pom.xml
      - name: Upload Test Result Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: ./**/logs
