# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JMAQS SnapShot Build

#on:
#  push:
#  tags:
#    -v*
on:
  push:
    branches: [master]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release notes
        id: release-drafter
        uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          version=${{steps.release-drafter.outputs.tag_name}}
          echo "${version//v}" >> version.txt
      - name: Upload Version Number
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
  snapshot_build:
    runs-on: ubuntu-latest
    needs: update_release_draft
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v1
        with:
          name: version
      - name: Store version number in environment variable
        shell: bash
        run: |
          value=`cat version/version.txt`
          echo ::set-env name=VERSION::$value
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2
      - name: Create settings file
        uses: InstaCode/maven-settings-xml-action@v9
        with:
          servers: '[{"id": "ossrh", "username": "jason-edstrom", "password": "${{secrets.OSSRH_PACKAGES}}"}]'
          profiles: '[{ "id": "sonar", "properties": { "sonar.organization":"${{secrets.SONAR_ORG}}", "sonar.host.url":"https://sonarcloud.io", "sonar.login": "${{secrets.SONAR_LOGIN}}"}}]'
      - name: Set Version to ${{env.VERSION}}-SNAPSHOT and Run Unit Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -Drevision="${{env.VERSION}}-SNAPSHOT" -Psonar -Pjacoco -T 1C verify install sonar:sonar -B -e -f pom.xml -fae -Dsonar.coverage.jacoco.xmlReportPaths="${{github.workspace}}/jmaqs-jacoco-reporting/target/site/jacoco-aggregate/jacoco.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy SnapShot Packages to Sonatype - Open Source
        run: mvn -Possrh deploy -DskipTests -B -e -f pom.xml
      - name: Upload Test Result Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: ./**/logs
